Assets/script.js
Assets/stylesheet.css
README.md

colour theme

---

Assets/script.js
Assets/stylesheet.css
README.md
index.html

added todo notes side bar

---

Assets/script.js
Assets/stylesheet.css
index.html

functional clear button to remove added to do list items 
a wonky non responsive budget form. :)

new budget form elements and a clear button for to do list

---

Assets/script.js
Assets/stylesheet.css
index.html

Js api cal

---

Assets/script.js
index.html

JS 
Dynamic table with labels and expenses

Dynamic JS and HTML Expense form

---

Assets/stylesheet.css

fixed errors

---

Assets/d3api.js
Assets/script.js
index.html

created new js files to work on separate

new js files

---

Assets/calendarAPI.js
index.html

Added google Calendar API AuthO and API KEY. Created functions to display calendar dynamically. Added ID to HTML to link calendar. 
Keep receiving a a error in console thats seems to be through linking. If you guys wouldnt mind taking a look to see if you see the problem

Google Calender added

---

Assets/calendarAPI.js
index.html

Added Google Calendar into HTML code to display dynamically. Functions were not calling proper var's.

Fixed calendarAPI.js file. 

---

README.md
index.html

layout edits

---

index.html

HTML expense form updated to add set form labels for mortage/rent, loans, etc.

input expense form changes

---

index.html

Updating my branch with partners changes.

Updating branch

---

Assets/script.js
Assets/stylesheet.css
index.html

added function to pull base colour themes

added base colour theme functions

---

Assets/d3api.js
index.html

this update is for the d3js.script file and is now functioning to allow user input to go from the budgeting from into the pie chart. 
Note: this information is still currently NOT going into the modal.

Pie Chart Pulling Data

---

Assets/cssreset.css
index.html

added css reset stylesheet

---

Assets/d3api.js
Assets/stylesheet.css
index.html

Fixed pie chart background to be transparent

chart layout

---

index.html

fixed layout todo/notes area not inline

fixed todo layout

---

README.md
index.html

Removed <p>calendar<p>. Changed background color on calendar to more suitable style.  Removed Unnecessary information on calendar also.

Changed calendar style.

---

Assets/stylesheet.css
index.html

organizing css

---

Assets/d3api.js
index.html

- Custom colours added to pie chart
- Modal taken away 
- lnitial labels added to pie chart

Chart Colors

---

Assets/d3api.js
README.md
index.html

Form overhaul

---

Assets/d3api.js
Assets/stylesheet.css
index.html

'See Total' and 'Authorize' buttons style update. 
Also consolidated  the '.input-group' redundant class listing in stylesheet.css

Buttons Update

---

Assets/stylesheet.css
index.html

testing error in vs

---

Assets/stylesheet.css
index.html

having errors in vs , fixing with ta help

file location error

---

Assets/stylesheet.css
index.html

Amount and Expense titles updated
padding on left side of pie chart
padding on right side of to do list and notes

Styling update

---

Assets/stylesheet.css
index.html

calendar now on top of to do list

z index added to calendar

---

Assets/stylesheet.css

Set up and start of media query information

Media query
